#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftD,         tmotorVex393HighSpeed_MC29, PIDControl, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightD,        tmotorVex393HighSpeed_MC29, PIDControl, encoderPort, I2C_2)
#pragma config(Motor,  port4,           lift,          tmotorVex393_MC29, PIDControl, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void initalizeGyro(){
	SensorType[gyro]=sensorNone;
	wait1Msec(1000);
	SensorType[gyro]=sensorGyro;
	wait1Msec(1000);
}




void rotate(int c, int angle){
	float targetAngle=c*angle*10;
	float rotateError;
	float rotateIntegral;
	float rotateLastError;
	float integralLimit=30;
	float integralActiveZoneRotation=100;
	float gyroKp=0.05;
	float gyroKi=0.05;
	float gyroKd=3;
	float gyroP;
	float gyroI;
	float gyroD;
	float power;
	SensorValue[in1]=0;
	clearTimer(T1);
	while(time1(T1)<1000 || abs(rotateError)>15){
		//PROPORTIONAL
		rotateError=targetAngle-SensorValue[in1];
		gyroP=rotateError*gyroKp;

		//INTEGRAL
		if(abs(rotateError)<integralActiveZoneRotation){
			rotateIntegral+=rotateError;
		}
		else{
			rotateIntegral=0;
		}
		gyroI=rotateIntegral*gyroKi;
		if(rotateIntegral>integralLimit){
			rotateIntegral=integralLimit;
		}

		//DERIVATIVE
		gyroD=(rotateError-rotateLastError)*gyroKd;
		rotateLastError=rotateError;
		if(rotateError==0){
			rotateLastError=0;
		}
		power=gyroP+gyroI+gyroD;
		motor[leftD]=-power;
		motor[rightD]=power;
	}

}



// PID controlled movement
// i: controls direction, set to 1 for forward and -1 for negative
// d: distance in # of tiles
// s: speed of motor from -127 to 127
void moveStraight(int i,long d,int s){
	clearTimer(T1);
	nMotorEncoder(leftD) = 0;
	nMotorEncoder(rightD) = 0;
	short dist = 700*d*i;
	//remember to change code based on wiring
	setMotorTarget(leftD,dist,s,false);
	setMotorTarget(rightD,dist,s,false);

	// Runs till target is reached
	while((!getMotorTargetCompleted(leftD) || !getMotorTargetCompleted(rightD))&time1[T1]<4000)
	{
		sleep(10);
	}
}

void liftX(int ticks){
	clearTimer(T1);
	nMotorEncoder[lift]=0;
	if(ticks < 0)
	{
		while(nMotorEncoder[lift]>ticks && time1[T1] < 5000)
		{
			motor[lift] = 127;
		}
	}
	else{
		while(nMotorEncoder[lift]<ticks && time1[T1]< 5000)
		{
			motor[lift]=-127;
		}
	}
	motor[lift]=0;
}



task main()
{
	//initializeGyro();
	liftX(-530);
	moveStraight(1,1.5,70);
	liftX(530);
	moveStraight(-1,1,70);
	//rotate(-180);
	//moveStraight(1,.5,70);
	//liftX(-530);
	//moveStraight(-1,.5,70);
	//rotate(45);
	//moveStraight(1,1,70);
	//rotate(90);
	//liftX(-530);
	//moveStraight(1,1.5,70);
	//liftX(530);
	//rotate(-160);
	//moveStraight(1,3,70);
	//liftX(-530);
	//moveStraight(-1,1,70);
	//rotate(150);
	//moveStraight(1,1.25,70);
	//liftX(530);
	//rotate(-150);
	//moveStraight(1,1,70);
	//liftX(-530);
	//moveStraight(-1,.5,70);
	//rotate(180);
	//moveStraight(1,4,70);
	//liftX(530);
	//rotate(10);
	//moveStraight(1,3,70);
	//liftX(-530);
	//moveStraight(-1,1,70);
	//rotate(160);
	//moveStraight(1,1,70);
	//liftX(530);
	//rotate(-160);
	//moveStraight(1,1.5,70);
	//liftX(-530);
	//moveStraight(-1,1,70);
	//rotate(-45);
	//moveStraight(1,3,70);
	//rotate(-90);
	//moveStraight(1,1.5,70);
	//liftX(530);
	//moveStraight(-1,1,70);
	//rotate(-180);
	//moveStraight(1,.5,70);
	//liftX(-530);
	//moveStraight(-1,2,70);
	//liftX(530);
}
