#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftD,         tmotorVex393HighSpeed_MC29, PIDControl, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightD,        tmotorVex393HighSpeed_MC29, PIDControl, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           lift,          tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void initalizeGyro(){
	SensorType[gyro]=sensorNone;
	wait1Msec(1000);
	SensorType[gyro]=sensorGyro;
	wait1Msec(1000);
}
void rotate(int c, int angle){
	float targetAngle=c*angle*10;
	float rotateError;
	float rotateIntegral;
	float rotateLastError;
	float integralLimit=30;
	float integralActiveZoneRotation=100;
	float gyroKp=0.05;
	float gyroKi=0.05;
	float gyroKd=3;
	float gyroP;
	float gyroI;
	float gyroD;
	float power;
	SensorValue[in1]=0;
	clearTimer(T1);
	while(time1(T1)<1000 || abs(rotateError)>15){
		//PROPORTIONAL
		rotateError=targetAngle-SensorValue[in1];
		gyroP=rotateError*gyroKp;

		//INTEGRAL
		if(abs(rotateError)<integralActiveZoneRotation){
			rotateIntegral+=rotateError;
		}
		else{
			rotateIntegral=0;
		}
		gyroI=rotateIntegral*gyroKi;
		if(rotateIntegral>integralLimit){
			rotateIntegral=integralLimit;
		}

		//DERIVATIVE
		gyroD=(rotateError-rotateLastError)*gyroKd;
		rotateLastError=rotateError;
		if(rotateError==0){
			rotateLastError=0;
		}
		power=gyroP+gyroI+gyroD;
		motor[leftD]=-power;
		motor[rightD]=power;
	}

}

task main()
{
	initalizeGyro();
	rotate(1,90);
	wait1Msec(100);
	rotate(1,90);
	wait1Msec(100);
	rotate(1,90);
	wait1Msec(100);
	rotate(1,90);
	wait1Msec(100);
}
