#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftD,         tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightD,        tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void initalizeGyro(){
	SensorType[gyro]=sensorNone;
	wait1Msec(2000);
	SensorType[gyro]=sensorGyro;
	wait1Msec(2000);
}
void rotate(int c, int angle){
	float targetAngle=c*angle*10;
	float rotateError;
	float rotateLastError;
	float gyroKp=0.5;
	float gyroKd=2;
	float gyroP;
	float gyroD;
	float power;
	clearTimer(T3);
	while(time1(T3)<1000 || abs(rotateError)>15){
		//PROPORTIONAL
		rotateError=targetAngle-SensorValue[in1];
		gyroP=rotateError*gyroKp;

		//INTEGRAL


		//DERIVATIVE
		gyroD=(rotateError-rotateLastError)*gyroKd;
		rotateLastError=rotateError;
		if(rotateError==0){
			rotateLastError=0;
		}
		power=gyroD+gyroP;
		motor[leftD]=-power;
		motor[rightD]=power;
	}

}
task main()
{
	initalizeGyro();
	rotate(1,90);

}
